### ISSUE TITLE
Light overlay number texture missing

### ISSUE THREAD

**Issue by Jim3535** [ThinkingStudios/MiniHUD-Forge#10]
![2023-11-09_15 58 16](https://github.com/ThinkingStudios/MiniHUD-Forge/assets/120746893/94e780a2-931e-492e-8b86-d974d79c1969)

I was able to fix it by copying `BoccHUD-0.1.1-mc1.20.1.jar\assets\minihud\textures\misc\light_level_numbers.png` to `BoccHUD-0.1.1-mc1.20.1.jar\assets\bocchud\textures\misc\light_level_numbers.png`.

So, it looks like either the texture is in the wrong place, or there is a path for it that's wrong in the code.

Environment:
* Prism Launcher version: 8.0
* Java is version 17.0.8, using 64 (amd64) architecture
* Minecraft 1.20.1
* Forge 47.2.0

Error:
`[09Nov2023 15:49:30.986] [Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: bocchud:textures/misc/light_level_numbers.png
java.io.FileNotFoundException: bocchud:textures/misc/light_level_numbers.png
	at net.minecraft.server.packs.resources.ResourceProvider.m_215590_(ResourceProvider.java:21) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.server.packs.resources.ResourceProvider.m_215593_(ResourceProvider.java:21) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture$TextureImage.m_118155_(SimpleTexture.java:83) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.m_6335_(SimpleTexture.java:58) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.m_6704_(SimpleTexture.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118515_(TextureManager.java:96) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118495_(TextureManager.java:66) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118506_(TextureManager.java:119) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at com.mojang.blaze3d.systems.RenderSystem._setShaderTexture(RenderSystem.java:1232) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.setShaderTexture(RenderSystem.java:1225) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at fi.dy.masa.malilib.render.RenderUtils.bindTexture(RenderUtils.java:80) ~[MaFgLib-0.1.3-mc1.20.1.jar%23161!/:0.1.3-mc1.20.1]
	at fi.dy.masa.minihud.renderer.OverlayRendererLightLevel.preRender(OverlayRendererLightLevel.java:108) ~[BoccHUD-0.1.1-mc1.20.1.jar%23159!/:0.1.1-mc1.20.1]
	at fi.dy.masa.minihud.renderer.OverlayRendererBase.draw(OverlayRendererBase.java:78) ~[BoccHUD-0.1.1-mc1.20.1.jar%23159!/:0.1.1-mc1.20.1]
	at fi.dy.masa.minihud.renderer.RenderContainer.draw(RenderContainer.java:122) ~[BoccHUD-0.1.1-mc1.20.1.jar%23159!/:0.1.1-mc1.20.1]
	at fi.dy.masa.minihud.renderer.RenderContainer.render(RenderContainer.java:66) ~[BoccHUD-0.1.1-mc1.20.1.jar%23159!/:0.1.1-mc1.20.1]
	at fi.dy.masa.minihud.renderer.OverlayRenderer.renderOverlays(OverlayRenderer.java:63) ~[BoccHUD-0.1.1-mc1.20.1.jar%23159!/:0.1.1-mc1.20.1]
	at fi.dy.masa.minihud.event.RenderHandler.onRenderWorldLast(RenderHandler.java:176) ~[BoccHUD-0.1.1-mc1.20.1.jar%23159!/:0.1.1-mc1.20.1]
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(RenderEventHandler.java:114) ~[MaFgLib-0.1.3-mc1.20.1.jar%23161!/:0.1.3-mc1.20.1]
	at net.minecraft.client.renderer.LevelRenderer.handler$zbh000$onRenderWorldLastNormal(LevelRenderer.java:3607) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1414) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:66) ~[?:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?]`

**Comment by Tim-Odermatt** [comment]
Here a temporary resourcepack fix I made, for the missing nummbers.
[Bocchud fixes.zip](https://github.com/ThinkingStudios/MiniHUD-Forge/files/13907936/Bocchud.fixes.zip)

**Comment by TexBlock** [comment]
fix in latest version
